name = "hypermind"
compatibility_date = "2025-01-20"

[[kv_namespaces]]
binding = "POSTS_KV"
id = "deaf6712754247d5bda1e96b62c811dd"

[[r2_buckets]]
binding = "IMAGES_R2"
bucket_name = "hypermind"

[observability]
enabled = true
